# routes.yml
index:
    path: /
    defaults: { _controller: '\Index\Controller\IndexController::indexAction' }
foo:
    path: /foo
    defaults: { _controller: 'Foo\Controller\FooController::indexAction' }

bar:
    path: /bar
    defaults: { _controller: 'Bar\Controller\BarController::indexAction' }

hello:
    path: /hello/{name}
    defaults: { _controller: 'Hello\Controller\HelloController::indexAction' }

entree:
    path: /admin/entree
    defaults: { _controller: 'Cieweb\Controller\EntreeController::indexAction' }

personneNouveau:
    path: /admin/personne/nouveau
    defaults: { _controller: 'Cieweb\Controller\PersonneNouveauController::indexAction' }
